/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
* 
* Description: 
*
*/

*
* Generated by XML2SYMBIAN.PL*


#ifndef _SYMBIAN_ISI_S60WLANISI_H_
#define _SYMBIAN_ISI_S60WLANISI_H_

#define S60_WLAN_ISI_VERSION_Z	 1
#define S60_WLAN_ISI_VERSION_Y	 0


//TABLES

//ConstantTable for FtdTable
#define FTD_SB_WLAN_OWN_MAC_ADDR                          	0x11                                              	
#define FTD_SB_WLAN_HW_VERSION                            	0x12                                              	
#define FTD_SB_WLAN_FW_VERSION                            	0x13                                              	
#define FTD_SB_WLAN_SSID                                  	0x14                                              	
#define FTD_SB_WLAN_AP_MAC_ADDR                           	0x15                                              	
#define FTD_SB_WLAN_CHANNEL                               	0x16                                              	
#define FTD_SB_WLAN_RSSI                                  	0x17                                              	
#define FTD_SB_WLAN_RATES_11B                             	0x18                                              	
#define FTD_SB_WLAN_RATES_11G                             	0x19                                              	
#define FTD_SB_WLAN_CAPABILITY_LSB                        	0x1A                                              	
#define FTD_SB_WLAN_CAPABILITY_MSB                        	0x1B                                              	
#define FTD_SB_WLAN_AV_TX_RATE                            	0x1C                                              	
#define FTD_SB_WLAN_AV_RX_RATE                            	0x1D                                              	
#define FTD_SB_WLAN_UL_THROUGHPUT                         	0x1E                                              	
#define FTD_SB_WLAN_DL_THROUGHPUT                         	0x1F                                              	
#define FTD_SB_WLAN_UL_BYTES                              	0x20                                              	
#define FTD_SB_WLAN_DL_BYTES                              	0x21                                              	
#define FTD_SB_WLAN_BLACKLIST_ADDR_1                      	0x22                                              	
#define FTD_SB_WLAN_BLACKLIST_ADDR_2                      	0x23                                              	
#define FTD_SB_WLAN_BLACKLIST_ADDR_3                      	0x24                                              	
#define FTD_SB_WLAN_BLACKLIST_ADDR_4                      	0x25                                              	
#define FTD_SB_WLAN_SEC_MODE                              	0x26                                              	
#define FTD_SB_WLAN_REG_DOMAIN                            	0x27                                              	
#define FTD_SB_WLAN_CONNECTION_STATE                      	0x28                                              	
#define FTD_SB_WLAN_TX_POWER                              	0x2B                                              	
#define FTD_SB_WLAN_POWER_SAVE                            	0x2C                                              	
#define FTD_SB_WLAN_TX_FRAMES                             	0x2D                                              	
#define FTD_SB_WLAN_RX_UC_FRAMES                          	0x2E                                              	
#define FTD_SB_WLAN_RX_MC_FRAMES                          	0x2F                                              	
#define FTD_SB_WLAN_TX_ERRORS                             	0x30                                              	
#define FTD_SB_WLAN_TX_RETRANS                            	0x31                                              	
#define FTD_SB_WLAN_RX_CRC_ERRORS                         	0x32                                              	
#define FTD_SB_WLAN_CONNECTIONS                           	0x33                                              	
#define FTD_SB_WLAN_CONNECTION_FAILS                      	0x34                                              	
#define FTD_SB_WLAN_ROAMINGS                              	0x35                                              	
#define FTD_SB_WLAN_COVERAGE_LOSSES                       	0x36                                              	
#define FTD_SB_WLAN_RESET_COUNTERS                        	0x37                                              	
#define FTD_SB_WLAN_RD_CONTROL_SET                        	0x38                                              	
#define FTD_SB_WLAN_RD_CONTROL_GET                        	0x39                                              	
#define FTD_SB_WLAN_ROAM_TIME_TOTAL                       	0x3A                                              	
#define FTD_SB_WLAN_ROAM_TIME_DATA_PATH                   	0x3B                                              	
#define FTD_SB_WLAN_ROAM_CAUSE                            	0x3C                                              	

#endif