/*
* Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/



// This file is autogenerated from operators.txt
// Generation date: 09-Apr-2010 08:13:42


struct TOperator
    {
    int iMNC;
    const char* iLatinName;
    const unsigned short* iUnicodeName;
    };

struct TCountry
    {
    int iMCC;
    const char* iCountryId;
    int iOperatorCount;
    const struct TOperator* iOperators;
    };

// UCS2 strings
const unsigned short uname_454_12[] = { 0x4E2D, 0x570B, 0x79FB, 0x52D5, 0x9999, 0x6E2F, 0 }; // CMHK
const unsigned short uname_454_18[] = { 0x8A0A, 0x806F, 0x96FB, 0x4FE1, 0 }; // CSL
const unsigned short uname_454_22[] = { 0x516B, 0x65B9, 0x901A, 0x8A0A, 0 }; // HK P PLUS
const unsigned short uname_455_0[] = { 0x6578, 0x78BC, 0x901A, 0 }; // SmarTone
const unsigned short uname_455_1[] = { 0x6FB3, 0x9580, 0x96FB, 0x8A0A, 0 }; // CTM
const unsigned short uname_460_0[] = { 0x4E2D, 0x56FD, 0x79FB, 0x52A8, 0 }; // CMCC
const unsigned short uname_460_1[] = { 0x4E2D, 0x56FD, 0x8054, 0x901A, 0 }; // CHN-UNICOM
const unsigned short uname_466_1[] = { 0x9060, 0x50B3, 0x96FB, 0x4FE1, 0 }; // FarEasTone
const unsigned short uname_466_6[] = { 0x6771, 0x69AE, 0x96FB, 0x4FE1, 0 }; // TUNTEX
const unsigned short uname_466_88[] = { 0x548C, 0x4FE1, 0x004F, 0x006E, 0x006C, 0x0069, 0x006E, 0x0065, 0 }; // KGT-Online
const unsigned short uname_466_89[] = { 0x5A01, 0x5BF6, 0x96FB, 0x4FE1, 0 }; // VIBO
const unsigned short uname_466_92[] = { 0x4E2D, 0x83EF, 0x96FB, 0x4FE1, 0 }; // Chunghwa
const unsigned short uname_466_93[] = { 0x6771, 0x4FE1, 0x96FB, 0x8A0A, 0 }; // MOBITAI
const unsigned short uname_466_97[] = { 0x53F0, 0x7063, 0x5927, 0x54E5, 0x5927, 0 }; // TW Mobile
const unsigned short uname_466_99[] = { 0x6CDB, 0x4E9E, 0x96FB, 0x4FE1, 0 }; // TransAsia

// Operator data
const TOperator operators_1[1] = { // 001
  { 1, "001 01", NULL },
};

const TOperator operators_2[1] = { // 002
  { 1, "002 01", NULL },
};

const TOperator operators_202[4] = { // GRC
  { 1, "COSMOTE", NULL },
  { 5, "vodafone GR", NULL },
  { 9, "GR Q-TELECOM", NULL },
  { 10, "TIM GR", NULL },
};

const TOperator operators_204[5] = { // NLD
  { 4, "vodafone NL", NULL },
  { 8, "NL KPN", NULL },
  { 12, "NL Telfort", NULL },
  { 16, "T-Mobile NL", NULL },
  { 20, "Orange NL", NULL },
};

const TOperator operators_206[3] = { // BEL
  { 1, "PROXIMUS", NULL },
  { 10, "Mobistar", NULL },
  { 20, "BASE", NULL },
};

const TOperator operators_208[6] = { // FRA
  { 1, "Orange F", NULL },
  { 2, "F - Contact", NULL },
  { 10, "F SFR", NULL },
  { 13, "F - Contact", NULL },
  { 20, "F BOUYGTEL", NULL },
  { 88, "F - Contact", NULL },
};

const TOperator operators_212[1] = { // MCO
  { 10, "Monaco", NULL },
};

const TOperator operators_213[1] = { // AND
  { 3, "STA-MOBILAND", NULL },
};

const TOperator operators_214[5] = { // ESP
  { 1, "vodafone ES", NULL },
  { 2, "movistar", NULL },
  { 3, "Orange", NULL },
  { 4, "Yoigo", NULL },
  { 7, "movistar", NULL },
};

const TOperator operators_216[3] = { // HU
  { 1, "H pannon 3G", NULL },
  { 30, "T-Mobile H", NULL },
  { 70, "vodafone HU", NULL },
};

const TOperator operators_218[3] = { // BIH
  { 3, "HT ERONET", NULL },
  { 5, "m:tel", NULL },
  { 90, "BHMobile", NULL },
};

const TOperator operators_219[3] = { // HRV
  { 1, "T-Mobile HR", NULL },
  { 2, "Tele2 HR", NULL },
  { 10, "HR VIP", NULL },
};

const TOperator operators_220[5] = { // SCG
  { 1, "Telenor SRB", NULL },
  { 2, "ProMonte", NULL },
  { 3, "MTS", NULL },
  { 4, "T-Mobile CG", NULL },
  { 5, "Vip SRB", NULL },
};

const TOperator operators_222[5] = { // ITA
  { 1, "TIM", NULL },
  { 10, "vodafone IT", NULL },
  { 88, "I WIND", NULL },
  { 98, "I BLU", NULL },
  { 99, "3 ITA", NULL },
};

const TOperator operators_226[4] = { // ROU
  { 1, "Vodafone RO", NULL },
  { 3, "RO COSMOTE", NULL },
  { 5, "Digi", NULL },
  { 10, "RO ORANGE", NULL },
};

const TOperator operators_228[5] = { // CHE
  { 1, "Swisscom", NULL },
  { 2, "Sunrise", NULL },
  { 3, "orange CH", NULL },
  { 7, "In&Phone", NULL },
  { 8, "T2", NULL },
};

const TOperator operators_230[3] = { // CZE
  { 1, "T-Mobile CZ", NULL },
  { 2, "O2 - CZ", NULL },
  { 3, "Vodafone CZ", NULL },
};

const TOperator operators_231[3] = { // SVK
  { 1, "Orange SK", NULL },
  { 2, "T-Mobile SK", NULL },
  { 6, "O2-SK", NULL },
};

const TOperator operators_232[6] = { // AUT
  { 1, "A1", NULL },
  { 3, "T-Mobile A", NULL },
  { 5, "Orange AT", NULL },
  { 7, "tele - ring", NULL },
  { 10, "3 AT", NULL },
  { 12, "Orange AT", NULL },
};

const TOperator operators_234[14] = { // GBR
  { 1, "UK01", NULL },
  { 3, "ATL-VOD", NULL },
  { 7, "C&W UK", NULL },
  { 10, "O2 - UK", NULL },
  { 15, "vodafone UK", NULL },
  { 19, "PMN UK", NULL },
  { 20, "3 UK", NULL },
  { 30, "T-Mobile UK", NULL },
  { 31, "T-Mobile UK", NULL },
  { 32, "T-Mobile UK", NULL },
  { 33, "Orange", NULL },
  { 50, "JT-Wave", NULL },
  { 55, "Sure", NULL },
  { 58, "MANX", NULL },
};

const TOperator operators_238[6] = { // DNK
  { 1, "TDC MOBIL", NULL },
  { 2, "Telenor DK", NULL },
  { 6, "3 DK", NULL },
  { 20, "TELIA DK", NULL },
  { 30, "Orange", NULL },
  { 77, "Telenor DK", NULL },
};

const TOperator operators_240[8] = { // SWE
  { 1, "TELIA", NULL },
  { 2, "3 SE", NULL },
  { 3, "Orange", NULL },
  { 4, "SWEDEN", NULL },
  { 5, "SWEDEN 3G", NULL },
  { 7, "Tele2 SE", NULL },
  { 8, "Telenor SE", NULL },
  { 10, "Spring", NULL },
};

const TOperator operators_242[4] = { // NOR
  { 1, "TELENOR", NULL },
  { 2, "N NetCom", NULL },
  { 3, "MTU", NULL },
  { 5, "Mobile N", NULL },
};

const TOperator operators_244[7] = { // FIN
  { 3, "dna", NULL },
  { 5, "elisa", NULL },
  { 7, "NOKIA", NULL },
  { 9, "FINNET", NULL },
  { 12, "dna", NULL },
  { 14, "FI AMT", NULL },
  { 91, "SONERA", NULL },
};

const TOperator operators_246[3] = { // LTU
  { 1, "OMNITEL LT", NULL },
  { 2, "BITE GSM", NULL },
  { 3, "Tele2 LT", NULL },
};

const TOperator operators_247[3] = { // LVA
  { 1, "LV LMT", NULL },
  { 2, "Tele2 LV", NULL },
  { 5, "BITE LV", NULL },
};

const TOperator operators_248[3] = { // EST
  { 1, "EE EMT", NULL },
  { 2, "EE elisa", NULL },
  { 3, "Tele2 EE", NULL },
};

const TOperator operators_250[24] = { // RUS
  { 1, "MTS", NULL },
  { 2, "MegaFon", NULL },
  { 3, "NCC", NULL },
  { 4, "RUS_SCN", NULL },
  { 5, "SCS", NULL },
  { 7, "SMARTS", NULL },
  { 10, "RUS DTC", NULL },
  { 11, "ORENSOT", NULL },
  { 12, "Far East", NULL },
  { 13, "KUGSM", NULL },
  { 14, "Di-ex", NULL },
  { 15, "SMARTS", NULL },
  { 16, "NTC", NULL },
  { 17, "Ermak RMS", NULL },
  { 19, "RUS: INDIGO", NULL },
  { 20, "TELE2 RU", NULL },
  { 28, "Beeline", NULL },
  { 35, "MOTIV", NULL },
  { 37, "KODOTEL", NULL },
  { 39, "Uraltel", NULL },
  { 44, "NC-GSM", NULL },
  { 92, "Primtel", NULL },
  { 93, "TXXI", NULL },
  { 99, "Beeline", NULL },
};

const TOperator operators_255[5] = { // UKR
  { 1, "MTS UKR", NULL },
  { 2, "Beeline UA", NULL },
  { 3, "KYIVSTAR", NULL },
  { 5, "UA-GT", NULL },
  { 6, "life:)", NULL },
};

const TOperator operators_257[4] = { // BLR
  { 1, "VELCOM", NULL },
  { 2, "MTS BY", NULL },
  { 4, "life:) BY", NULL },
  { 25, "BeST BY", NULL },
};

const TOperator operators_259[3] = { // MDA
  { 1, "Orange MD", NULL },
  { 2, "MD MOLDCELL", NULL },
  { 4, "MDA EVENTIS", NULL },
};

const TOperator operators_260[4] = { // POL
  { 1, "Plus", NULL },
  { 2, "Era", NULL },
  { 3, "Orange PL", NULL },
  { 6, "Play", NULL },
};

const TOperator operators_262[7] = { // DEU
  { 1, "Telekom.de", NULL },
  { 2, "Vodafone.de", NULL },
  { 3, "E-Plus", NULL },
  { 7, "o2 - de", NULL },
  { 8, "o2 - de", NULL },
  { 13, "MobilCom", NULL },
  { 14, "Quam", NULL },
};

const TOperator operators_266[2] = { // GIB
  { 1, "GIBTEL", NULL },
  { 6, "CTS", NULL },
};

const TOperator operators_268[3] = { // PRT
  { 1, "vodafone P", NULL },
  { 3, "OPTIMUS", NULL },
  { 6, "TMN", NULL },
};

const TOperator operators_270[3] = { // LUX
  { 1, "LUXGSM", NULL },
  { 77, "TANGO", NULL },
  { 99, "L Orange-LU", NULL },
};

const TOperator operators_272[4] = { // IRL
  { 1, "vodafone IE", NULL },
  { 2, "O2 IRL", NULL },
  { 3, "METEOR", NULL },
  { 5, "3 IRL", NULL },
};

const TOperator operators_274[6] = { // ISL
  { 1, "Siminn", NULL },
  { 2, "Vodafone", NULL },
  { 4, "Viking", NULL },
  { 7, "IS-IceCell", NULL },
  { 8, "On-waves", NULL },
  { 11, "NOVA IS", NULL },
};

const TOperator operators_276[4] = { // ALB
  { 1, "AMC - AL", NULL },
  { 2, "vodafone AL", NULL },
  { 3, "EAGLE AL", NULL },
  { 4, "PLUS AL", NULL },
};

const TOperator operators_278[3] = { // MLT
  { 1, "vodafone MT", NULL },
  { 21, "go mobile", NULL },
  { 77, "3GT MT", NULL },
};

const TOperator operators_280[2] = { // CYP
  { 1, "CYTAVODA", NULL },
  { 10, "MTN", NULL },
};

const TOperator operators_282[4] = { // GEO
  { 1, "GEOCELL", NULL },
  { 2, "MAGTI GSM", NULL },
  { 3, "GEO 03", NULL },
  { 4, "BEELINE GE", NULL },
};

const TOperator operators_283[3] = { // ARM
  { 1, "Beeline AM", NULL },
  { 4, "RA 04", NULL },
  { 5, "MTS ARM", NULL },
};

const TOperator operators_284[3] = { // BGR
  { 1, "M-Tel BG", NULL },
  { 3, "vivatel", NULL },
  { 5, "BG GLOBUL", NULL },
};

const TOperator operators_286[4] = { // TUR
  { 1, "TURKCELL", NULL },
  { 2, "VODAFONE TR", NULL },
  { 3, "AVEA", NULL },
  { 4, "TR AYCELL", NULL },
};

const TOperator operators_288[2] = { // FRO
  { 1, "FT-GSM", NULL },
  { 2, "VODAFONE FO", NULL },
};

const TOperator operators_290[1] = { // GRL
  { 1, "TELE GRL", NULL },
};

const TOperator operators_292[1] = { // RSM
  { 66, "SMT", NULL },
};

const TOperator operators_293[4] = { // SVN
  { 40, "Si.mobil", NULL },
  { 41, "MOBITEL", NULL },
  { 64, "T-2", NULL },
  { 70, "SI TUSMOBIL", NULL },
};

const TOperator operators_294[3] = { // MKD
  { 1, "T-Mobile MK", NULL },
  { 2, "MKD COSMOFON", NULL },
  { 3, "Vip MKD", NULL },
};

const TOperator operators_295[4] = { // LIE
  { 1, "SwisscomFL", NULL },
  { 2, "Orange FL", NULL },
  { 5, "FL1", NULL },
  { 77, "LI TANGO", NULL },
};

const TOperator operators_302[9] = { // CAN
  { 220, "TELUS", NULL },
  { 350, "FIRST", NULL },
  { 370, "Fido", NULL },
  { 380, "DMTS GSM", NULL },
  { 490, "WIND", NULL },
  { 610, "Bell", NULL },
  { 720, "ROGERS", NULL },
  { 730, "TStarSol", NULL },
  { 880, "3G Plus", NULL },
};

const TOperator operators_308[2] = { // SPM
  { 1, "SPM AMERIS", NULL },
  { 2, "SPM-PROSODIE", NULL },
};

const TOperator operators_310[79] = { // USA
  { 0, "Mid-Tex", NULL },
  { 11, "WTTCKy", NULL },
  { 20, "Union Tel", NULL },
  { 26, "T-Mobile", NULL },
  { 30, "CENT USA", NULL },
  { 31, "T-Mobile", NULL },
  { 32, "IT&E", NULL },
  { 38, "AT&T", NULL },
  { 40, "CONCHO", NULL },
  { 46, "USA SIMMETRY", NULL },
  { 50, "DIGICEL", NULL },
  { 58, "T-Mobile", NULL },
  { 64, "ARDGMC", NULL },
  { 70, "Highland", NULL },
  { 80, "Corr", NULL },
  { 90, "Edge", NULL },
  { 100, "US PLATEAU", NULL },
  { 150, "AT&T", NULL },
  { 160, "T-Mobile", NULL },
  { 170, "AT&T", NULL },
  { 180, "West Central", NULL },
  { 190, "D HARBOR", NULL },
  { 200, "T-Mobile", NULL },
  { 210, "T-Mobile", NULL },
  { 220, "T-Mobile", NULL },
  { 230, "T-Mobile", NULL },
  { 240, "T-Mobile", NULL },
  { 250, "T-Mobile", NULL },
  { 260, "T-Mobile", NULL },
  { 270, "T-Mobile", NULL },
  { 280, "T-Mobile", NULL },
  { 290, "NEP Wireless", NULL },
  { 300, "iSmartUS", NULL },
  { 310, "T-Mobile", NULL },
  { 311, "FARMERS", NULL },
  { 320, "Cell", NULL },
  { 330, "Cellular One", NULL },
  { 340, "WestLink", NULL },
  { 350, "Carolina", NULL },
  { 380, "AT&T", NULL },
  { 390, "Cell1ET", NULL },
  { 400, "USA iCAN", NULL },
  { 410, "AT&T", NULL },
  { 420, "CBW", NULL },
  { 450, "NECCI", NULL },
  { 460, "USA ONELINK", NULL },
  { 470, "DOCOMOPA", NULL },
  { 490, "T-Mobile", NULL },
  { 500, "PSC Wireless", NULL },
  { 530, "IWS", NULL },
  { 560, "Cell One", NULL },
  { 580, "T-Mobile", NULL },
  { 570, "Chinook", NULL },
  { 590, "ROAMING", NULL },
  { 610, "EpicTouch", NULL },
  { 630, "AmeriLink", NULL },
  { 640, "Einstein PCS", NULL },
  { 650, "Jasper", NULL },
  { 660, "T-Mobile", NULL },
  { 670, "W 2000 PCS", NULL },
  { 680, "NPI Wireless", NULL },
  { 690, "IMMIX", NULL },
  { 700, "USA BIGFOOT", NULL },
  { 710, "USA ASTAC", NULL },
  { 740, "Telemetrix", NULL },
  { 760, "PTSI", NULL },
  { 770, "IWS", NULL },
  { 780, "AirLink PCS", NULL },
  { 790, "Pinpoint", NULL },
  { 800, "T-Mobile", NULL },
  { 870, "PACE", NULL },
  { 880, "USAACSI", NULL },
  { 890, "USA Unicel", NULL },
  { 900, "TXCELL", NULL },
  { 910, "USAFC", NULL },
  { 940, "DCT", NULL },
  { 950, "XIT", NULL },
  { 980, "AT&T", NULL },
  { 990, "Cingular", NULL },
};

const TOperator operators_311[25] = { // USA
  { 0, "Mid-Tex", NULL },
  { 30, "Indigo", NULL },
  { 40, "Commnet", NULL },
  { 70, "USAEC", NULL },
  { 80, "PINECell", NULL },
  { 90, "USASXLP", NULL },
  { 110, "High Plains", NULL },
  { 130, "C1AMARIL", NULL },
  { 140, "Sprocket", NULL },
  { 150, "Wilkes USA", NULL },
  { 160, "EMW", NULL },
  { 170, "PetroCom", NULL },
  { 180, "AT&T", NULL },
  { 190, "USAC1ECI", NULL },
  { 210, "FARMERS", NULL },
  { 240, "USACWCI", NULL },
  { 250, "USA i CAN", NULL },
  { 310, "LamarCel", NULL },
  { 330, "BTW", NULL },
  { 360, "STELERA", NULL },
  { 370, "GCI", NULL },
  { 500, "MOSAIC", NULL },
  { 530, "USANCW", NULL },
  { 540, "US Proximiti", NULL },
  { 720, "MainePCS", NULL },
};

const TOperator operators_330[1] = { // PRI
  { 110, "PR Claro", NULL },
};

const TOperator operators_332[1] = { // USA
  { 11, "Blue Sky", NULL },
};

const TOperator operators_334[2] = { // MEX
  { 3, "movistar", NULL },
  { 20, "TELCEL GSM", NULL },
};

const TOperator operators_338[4] = { // JAM
  { 5, "DIGICEL", NULL },
  { 20, "C&W", NULL },
  { 70, "CLARO JAM", NULL },
  { 180, "C&W", NULL },
};

const TOperator operators_340[5] = { // FRA
  { 1, "F-Orange", NULL },
  { 2, "ONLY", NULL },
  { 3, "CHIPPIE", NULL },
  { 8, "DAUPHIN", NULL },
  { 20, "DIGICEL", NULL },
};

const TOperator operators_342[4] = { // BRB
  { 50, "Digicel", NULL },
  { 600, "C&W", NULL },
  { 750, "DIGICEL", NULL },
  { 810, "Cingular", NULL },
};

const TOperator operators_344[3] = { // ATG
  { 30, "APUA-PCS", NULL },
  { 920, "C&W", NULL },
  { 930, "Cingular", NULL },
};

const TOperator operators_346[1] = { // CYM
  { 140, "LIME", NULL },
};

const TOperator operators_348[2] = { // VGB
  { 170, "C&W", NULL },
  { 570, "CCTBVI", NULL },
};

const TOperator operators_350[4] = { // BDA
  { 0, "CellularOne", NULL },
  { 1, "TELECOM BDA", NULL },
  { 2, "M3 WIRELESS", NULL },
  { 10, "Cingular", NULL },
};

const TOperator operators_352[4] = { // GRD
  { 30, "Cingular", NULL },
  { 50, "Digicel", NULL },
  { 110, "C&W", NULL },
  { 130, "TWTCGN", NULL },
};

const TOperator operators_354[1] = { // MS
  { 860, "LIME", NULL },
};

const TOperator operators_356[1] = { // KNA
  { 110, "LIME", NULL },
};

const TOperator operators_358[3] = { // SLU
  { 30, "Cingular", NULL },
  { 50, "DIGICEL", NULL },
  { 110, "C&W", NULL },
};

const TOperator operators_360[3] = { // VCT
  { 10, "Cingular", NULL },
  { 70, "DIGICEL", NULL },
  { 110, "C&W", NULL },
};

const TOperator operators_362[5] = { // ANT
  { 51, "Telcell GSM", NULL },
  { 69, "CT GSM", NULL },
  { 91, "UTS", NULL },
  { 630, "Cingular", NULL },
  { 951, "ANT", NULL },
};

const TOperator operators_363[2] = { // ABW
  { 1, "SETAR GSM", NULL },
  { 20, "DIGICEL", NULL },
};

const TOperator operators_364[1] = { // BHS
  { 39, "BaTelCell", NULL },
};

const TOperator operators_365[1] = { // AIA
  { 840, "C&W", NULL },
};

const TOperator operators_366[2] = { // DMA
  { 20, "Cingular", NULL },
  { 110, "C&W", NULL },
};

const TOperator operators_368[1] = { // CUB
  { 1, "CUBACEL", NULL },
};

const TOperator operators_370[2] = { // DOM
  { 1, "orange", NULL },
  { 2, "CLARO DOM", NULL },
};

const TOperator operators_372[1] = { // HTI
  { 1, "COMCEL", NULL },
};

const TOperator operators_374[1] = { // TTO
  { 12, "TSTT", NULL },
};

const TOperator operators_376[2] = { // TCA
  { 350, "C&W", NULL },
  { 352, "ICOM TCI", NULL },
};

const TOperator operators_400[3] = { // AZE
  { 1, "ACELL", NULL },
  { 2, "BKCELL", NULL },
  { 4, "AZ Nar", NULL },
};

const TOperator operators_401[3] = { // KAZ
  { 1, "Beeline KZ", NULL },
  { 2, "KZ KCELL", NULL },
  { 77, "NEO-KZ", NULL },
};

const TOperator operators_402[2] = { // BTN
  { 17, "BT B-Mobile", NULL },
  { 77, "TASHICELL", NULL },
};

const TOperator operators_404[91] = { // IND
  { 1, "Vodafone IN", NULL },
  { 2, "AirTel", NULL },
  { 3, "AirTel", NULL },
  { 4, "IDEA", NULL },
  { 5, "Vodafone IN", NULL },
  { 7, "IDEA", NULL },
  { 8, "USHAFONE", NULL },
  { 9, "Reliance", NULL },
  { 10, "AirTel", NULL },
  { 11, "Vodafone IN", NULL },
  { 12, "IDEA", NULL },
  { 13, "Vodafone IN", NULL },
  { 14, "INA SPICE", NULL },
  { 15, "Vodafone IN", NULL },
  { 16, "AirTel", NULL },
  { 17, "AIRCEL", NULL },
  { 18, "Reliance", NULL },
  { 19, "IDEA", NULL },
  { 20, "Vodafone IN", NULL },
  { 21, "BPL MOBILE", NULL },
  { 22, "IDEA", NULL },
  { 23, "USHAFONE", NULL },
  { 24, "IDEA", NULL },
  { 25, "AIRCEL", NULL },
  { 26, "USHAFONE", NULL },
  { 27, "Vodafone IN", NULL },
  { 28, "AIRCEL", NULL },
  { 29, "AIRCEL", NULL },
  { 30, "Vodafone IN", NULL },
  { 31, "AirTel", NULL },
  { 32, "USHAFONE", NULL },
  { 33, "AIRCEL", NULL },
  { 34, "CellOne", NULL },
  { 35, "AIRCEL", NULL },
  { 36, "Reliance", NULL },
  { 37, "AIRCEL", NULL },
  { 38, "CellOne", NULL },
  { 40, "IND AIRTEL", NULL },
  { 41, "AIRCEL", NULL },
  { 42, "AIRCEL", NULL },
  { 43, "Vodafone IN", NULL },
  { 44, "SPICE", NULL },
  { 45, "AirTel", NULL },
  { 46, "Vodafone IN", NULL },
  { 49, "AirTel", NULL },
  { 50, "Reliance", NULL },
  { 51, "CellOne", NULL },
  { 52, "Reliance", NULL },
  { 53, "CellOne", NULL },
  { 54, "CellOne", NULL },
  { 55, "CellOne", NULL },
  { 56, "IDEA", NULL },
  { 57, "CellOne", NULL },
  { 58, "CellOne", NULL },
  { 59, "CellOne", NULL },
  { 60, "Vodafone IN", NULL },
  { 62, "CellOne", NULL },
  { 64, "CellOne", NULL },
  { 66, "CellOne", NULL },
  { 67, "Reliance", NULL },
  { 68, "IN-DOLPHIN", NULL },
  { 69, "DOLPHIN", NULL },
  { 70, "Oasis", NULL },
  { 71, "CellOne", NULL },
  { 72, "CellOne", NULL },
  { 73, "CellOne", NULL },
  { 74, "CellOne", NULL },
  { 75, "CellOne", NULL },
  { 76, "CellOne", NULL },
  { 77, "CellOne", NULL },
  { 78, "IDEA", NULL },
  { 79, "CellOne", NULL },
  { 80, "CellOne", NULL },
  { 81, "CellOne", NULL },
  { 82, "IDEA", NULL },
  { 83, "Reliance", NULL },
  { 84, "Vodafone IN", NULL },
  { 85, "Reliance", NULL },
  { 86, "Vodafone IN", NULL },
  { 87, "IDEA", NULL },
  { 88, "Vodafone IN", NULL },
  { 89, "IDEA", NULL },
  { 90, "AirTel", NULL },
  { 91, "AirCel", NULL },
  { 92, "AirTel", NULL },
  { 93, "AirTel", NULL },
  { 94, "AirTel", NULL },
  { 95, "AirTel", NULL },
  { 96, "AirTel", NULL },
  { 97, "AirTel", NULL },
  { 98, "AirTel", NULL },
};

const TOperator operators_405[147] = { // IND
  { 1, "Reliance", NULL },
  { 5, "Reliance", NULL },
  { 6, "Reliance", NULL },
  { 7, "Reliance", NULL },
  { 9, "Reliance", NULL },
  { 10, "Reliance", NULL },
  { 11, "Reliance", NULL },
  { 13, "Reliance", NULL },
  { 15, "Reliance", NULL },
  { 18, "Reliance", NULL },
  { 19, "Reliance", NULL },
  { 20, "Reliance", NULL },
  { 21, "Reliance", NULL },
  { 22, "Reliance", NULL },
  { 25, "TATA GSM", NULL },
  { 27, "TATA GSM", NULL },
  { 29, "TATA GSM", NULL },
  { 30, "TATA GSM", NULL },
  { 31, "TATA GSM", NULL },
  { 32, "TATA GSM", NULL },
  { 34, "TATA GSM", NULL },
  { 35, "TATA GSM", NULL },
  { 36, "TATA GSM", NULL },
  { 37, "TATA GSM", NULL },
  { 38, "TATA GSM", NULL },
  { 39, "TATA GSM", NULL },
  { 41, "TATA GSM", NULL },
  { 42, "TATA GSM", NULL },
  { 43, "TATA GSM", NULL },
  { 44, "TATA GSM", NULL },
  { 45, "TATA GSM", NULL },
  { 46, "TATA GSM", NULL },
  { 47, "TATA GSM", NULL },
  { 50, "Reliance", NULL },
  { 51, "IND AirTel", NULL },
  { 52, "IND AirTel", NULL },
  { 53, "IND AirTel", NULL },
  { 54, "IND AirTel", NULL },
  { 55, "IND AirTel", NULL },
  { 56, "IND AirTel", NULL },
  { 66, "Vodafone IN", NULL },
  { 67, "Vodafone IN", NULL },
  { 70, "IDEA", NULL },
  { 750, "Vodafone IN", NULL },
  { 751, "Vodafone IN", NULL },
  { 752, "Vodafone IN", NULL },
  { 753, "Vodafone IN", NULL },
  { 754, "Vodafone IN", NULL },
  { 755, "Vodafone IN", NULL },
  { 756, "Vodafone IN", NULL },
  { 799, "IDEA", NULL },
  { 800, "Aircel", NULL },
  { 801, "Aircel", NULL },
  { 802, "Aircel", NULL },
  { 803, "Aircel", NULL },
  { 804, "Aircel", NULL },
  { 805, "Aircel", NULL },
  { 806, "Aircel", NULL },
  { 807, "Aircel", NULL },
  { 808, "Aircel", NULL },
  { 809, "Aircel", NULL },
  { 810, "Aircel", NULL },
  { 811, "Aircel", NULL },
  { 812, "Aircel", NULL },
  { 813, "IN UNITECH", NULL },
  { 814, "IN UNITECH", NULL },
  { 815, "IN UNITECH", NULL },
  { 816, "IN UNITECH", NULL },
  { 817, "IN UNITECH", NULL },
  { 818, "IN UNITECH", NULL },
  { 819, "IN UNITECH", NULL },
  { 820, "IN UNITECH", NULL },
  { 821, "IN UNITECH", NULL },
  { 822, "IN UNITECH", NULL },
  { 823, "VIDEOCON", NULL },
  { 824, "VIDEOCON", NULL },
  { 825, "VIDEOCON", NULL },
  { 827, "VIDEOCON", NULL },
  { 828, "VIDEOCON", NULL },
  { 829, "VIDEOCON", NULL },
  { 830, "VIDEOCON", NULL },
  { 831, "VIDEOCON", NULL },
  { 832, "VIDEOCON", NULL },
  { 833, "VIDEOCON", NULL },
  { 834, "VIDEOCON", NULL },
  { 835, "VIDEOCON", NULL },
  { 836, "VIDEOCON", NULL },
  { 837, "VIDEOCON", NULL },
  { 838, "VIDEOCON", NULL },
  { 839, "VIDEOCON", NULL },
  { 840, "VIDEOCON", NULL },
  { 841, "VIDEOCON", NULL },
  { 842, "VIDEOCON", NULL },
  { 843, "VIDEOCON", NULL },
  { 844, "Unitech", NULL },
  { 845, "IDEA", NULL },
  { 846, "IDEA", NULL },
  { 848, "IDEA", NULL },
  { 849, "IDEA", NULL },
  { 850, "IDEA", NULL },
  { 852, "IDEA", NULL },
  { 853, "IDEA", NULL },
  { 854, "LoopMobile", NULL },
  { 855, "LoopMobile", NULL },
  { 856, "LoopMobile", NULL },
  { 857, "LoopMobile", NULL },
  { 858, "LoopMobile", NULL },
  { 859, "LoopMobile", NULL },
  { 860, "LoopMobile", NULL },
  { 861, "LoopMobile", NULL },
  { 862, "LoopMobile", NULL },
  { 863, "LoopMobile", NULL },
  { 864, "LoopMobile", NULL },
  { 865, "LoopMobile", NULL },
  { 866, "LoopMobile", NULL },
  { 867, "LoopMobile", NULL },
  { 868, "LoopMobile", NULL },
  { 869, "LoopMobile", NULL },
  { 870, "LoopMobile", NULL },
  { 871, "LoopMobile", NULL },
  { 872, "LoopMobile", NULL },
  { 873, "LoopMobile", NULL },
  { 874, "LoopMobile", NULL },
  { 875, "IN UNITECH", NULL },
  { 876, "IN UNITECH", NULL },
  { 877, "IN UNITECH", NULL },
  { 878, "IN UNITECH", NULL },
  { 879, "IN UNITECH", NULL },
  { 880, "IN UNITECH", NULL },
  { 912, "etisalat", NULL },
  { 913, "etisalat", NULL },
  { 914, "etisalat", NULL },
  { 915, "etisalat", NULL },
  { 916, "etisalat", NULL },
  { 917, "etisalat", NULL },
  { 918, "etisalat", NULL },
  { 919, "etisalat", NULL },
  { 920, "etisalat", NULL },
  { 921, "etisalat", NULL },
  { 922, "etisalat", NULL },
  { 923, "etisalat", NULL },
  { 924, "etisalat", NULL },
  { 925, "IN UNITECH", NULL },
  { 926, "IN UNITECH", NULL },
  { 927, "IN UNITECH", NULL },
  { 928, "IN UNITECH", NULL },
  { 929, "IN UNITECH", NULL },
};

const TOperator operators_410[5] = { // PAK
  { 1, "Mobilink", NULL },
  { 3, "PK-UFONE", NULL },
  { 4, "ZONG", NULL },
  { 6, "Telenor PK", NULL },
  { 7, "WaridTel", NULL },
};

const TOperator operators_412[4] = { // AFG
  { 1, "AF AWCC", NULL },
  { 20, "ROSHAN", NULL },
  { 40, "MTN AF", NULL },
  { 50, "Etisalat Af", NULL },
};

const TOperator operators_413[6] = { // SRI
  { 1, "Mobitel", NULL },
  { 2, "DIALOG", NULL },
  { 3, "SRI Etisalat", NULL },
  { 5, "SRI AIRTEL", NULL },
  { 8, "Hutch", NULL },
  { 71, "LK Mobitel", NULL },
};

const TOperator operators_414[1] = { // MMR
  { 1, "MPTGSM", NULL },
};

const TOperator operators_415[3] = { // LBN
  { 1, "alfa", NULL },
  { 3, "MTC LIBAN", NULL },
  { 5, "OM", NULL },
};

const TOperator operators_416[3] = { // JOR
  { 1, "zain JO", NULL },
  { 3, "UMNIAH", NULL },
  { 77, "Orange JO", NULL },
};

const TOperator operators_417[4] = { // SYR
  { 1, "SYRIATEL", NULL },
  { 2, "MTN", NULL },
  { 9, "MOBILE", NULL },
  { 93, "SYRIATEL", NULL },
};

const TOperator operators_418[5] = { // IRQ
  { 5, "ASIACELL", NULL },
  { 20, "zain IQ", NULL },
  { 30, "IRAQNA", NULL },
  { 40, "KOREK", NULL },
  { 82, "SanaTel", NULL },
};

const TOperator operators_419[3] = { // KWT
  { 2, "Zain KW", NULL },
  { 3, "WATANIYA", NULL },
  { 4, "VIVA", NULL },
};

const TOperator operators_420[3] = { // KSA
  { 1, "STC", NULL },
  { 3, "mobily-KSA", NULL },
  { 7, "KSA EAE", NULL },
};

const TOperator operators_421[3] = { // YEM
  { 1, "SabaFon", NULL },
  { 2, "MTN", NULL },
  { 700, "YemYY", NULL },
};

const TOperator operators_422[2] = { // OMN
  { 2, "OMAN MOBILE", NULL },
  { 3, "nawras", NULL },
};

const TOperator operators_424[3] = { // UAE
  { 2, "ETISALAT", NULL },
  { 3, "du", NULL },
  { 5, "Thuraya", NULL },
};

const TOperator operators_425[5] = { // ISR
  { 1, "IL ORANGE", NULL },
  { 2, "Cellcom", NULL },
  { 3, "IL Pelephone", NULL },
  { 5, "JAWWAL", NULL },
  { 6, "WM", NULL },
};

const TOperator operators_426[3] = { // BHR
  { 1, "BATELCO", NULL },
  { 2, "zain BH", NULL },
  { 4, "VIVA BH", NULL },
};

const TOperator operators_427[2] = { // QAT
  { 1, "Qat - Qtel", NULL },
  { 2, "vodafone", NULL },
};

const TOperator operators_428[2] = { // MNG
  { 88, "UNTLMN", NULL },
  { 99, "MN MobiCom", NULL },
};

const TOperator operators_429[1] = { // NPL
  { 2, "Ncell", NULL },
};

const TOperator operators_432[5] = { // IRN
  { 11, "IR-TCI", NULL },
  { 14, "IR KISH", NULL },
  { 19, "IR MTCE", NULL },
  { 32, "Iran Taliya", NULL },
  { 35, "MTN Irancell", NULL },
};

const TOperator operators_434[6] = { // UZB
  { 0, "UZMACOM", NULL },
  { 1, "BUZTEL", NULL },
  { 2, "UZMACOM", NULL },
  { 4, "Beeline UZ", NULL },
  { 5, "UZB Ucell", NULL },
  { 7, "UZB MTS", NULL },
};

const TOperator operators_436[7] = { // TJK
  { 1, "TCELL", NULL },
  { 2, "TCELL", NULL },
  { 3, "TJK MLT", NULL },
  { 4, "Babilon-M", NULL },
  { 5, "BEELINE TJ", NULL },
  { 12, "INDIGO-T", NULL },
  { 91, "BEELINE", NULL },
};

const TOperator operators_437[3] = { // KGZ
  { 1, "BITEL", NULL },
  { 5, "MEGACOM", NULL },
  { 9, "O!", NULL },
};

const TOperator operators_438[1] = { // TKM
  { 1, "MTS TM", NULL },
};

const TOperator operators_440[3] = { // JPN
  { 0, "JPN EMOBILE", NULL },
  { 10, "JP DOCOMO", NULL },
  { 20, "SoftBank", NULL },
};

const TOperator operators_450[3] = { // KOR
  { 2, "KT", NULL },
  { 5, "SKT", NULL },
  { 8, "KT", NULL },
};

const TOperator operators_452[4] = { // VMN
  { 1, "VN MOBIFONE", NULL },
  { 2, "VN VINAPHONE", NULL },
  { 4, "VIETTEL", NULL },
  { 5, "VNMOBILE", NULL },
};

const TOperator operators_454[13] = { // HKG
  { 0, "CSL", NULL },
  { 2, "CSL", NULL },
  { 3, "3 HK", NULL },
  { 4, "3(2G)", NULL },
  { 6, "SMC-Voda", NULL },
  { 10, "CSL", NULL },
  { 12, "CMHK", uname_454_12 },
  { 15, "454-15", NULL },
  { 16, "PCCW", NULL },
  { 18, "CSL", uname_454_18 },
  { 19, "PCCW", NULL },
  { 20, "Orange", NULL },
  { 22, "HK P PLUS", uname_454_22 },
};

const TOperator operators_455[5] = { // MAC
  { 0, "SmarTone", uname_455_0 },
  { 1, "CTM", uname_455_1 },
  { 3, "HT Macau", NULL },
  { 4, "CTM", NULL },
  { 5, "3 Macau", NULL },
};

const TOperator operators_456[8] = { // KHM
  { 1, "MOBITEL", NULL },
  { 2, "hello", NULL },
  { 4, "CADCOMMS", NULL },
  { 5, "STAR CELL", NULL },
  { 6, "SMART", NULL },
  { 8, "Metfone", NULL },
  { 9, "Beeline KH", NULL },
  { 18, "Mfone", NULL },
};

const TOperator operators_457[4] = { // LAO
  { 1, "LAO GSM", NULL },
  { 2, "ETLMNW", NULL },
  { 3, "Unitel", NULL },
  { 8, "TIGO LAO", NULL },
};

const TOperator operators_460[2] = { // CHN
  { 0, "CMCC", uname_460_0 },
  { 1, "CHN-UNICOM", uname_460_1 },
};

const TOperator operators_466[8] = { // TWN
  { 1, "FarEasTone", uname_466_1 },
  { 6, "TUNTEX", uname_466_6 },
  { 88, "KGT-Online", uname_466_88 },
  { 89, "VIBO", uname_466_89 },
  { 92, "Chunghwa", uname_466_92 },
  { 93, "MOBITAI", uname_466_93 },
  { 97, "TW Mobile", uname_466_97 },
  { 99, "TransAsia", uname_466_99 },
};

const TOperator operators_467[1] = { // PRK
  { 193, "KP SUN", NULL },
};

const TOperator operators_470[5] = { // BGD
  { 1, "grameenphone", NULL },
  { 2, "AKTEL", NULL },
  { 3, "Banglalink", NULL },
  { 4, "BGD bMobile", NULL },
  { 7, "WARID BD", NULL },
};

const TOperator operators_472[2] = { // MDV
  { 1, "DHIMOBILE", NULL },
  { 2, "WATANIYA", NULL },
};

const TOperator operators_502[8] = { // MYS
  { 2, "BINARIANG", NULL },
  { 10, "TIME3G", NULL },
  { 12, "MY MAXIS", NULL },
  { 13, "MY CELCOM 3G", NULL },
  { 16, "DiGi", NULL },
  { 17, "TIMECel", NULL },
  { 18, "U MOBILE", NULL },
  { 19, "MY CELCOM", NULL },
};

const TOperator operators_505[6] = { // AUS
  { 1, "Telstra", NULL },
  { 2, "YES OPTUS", NULL },
  { 3, "vodafone AU", NULL },
  { 6, "3TELSTRA", NULL },
  { 8, "One.Tel", NULL },
  { 10, "NT", NULL },
};

const TOperator operators_510[6] = { // IDN
  { 1, "INDOSAT", NULL },
  { 8, "AXIS", NULL },
  { 10, "TELKOMSEL", NULL },
  { 11, "IND XL", NULL },
  { 21, "INDOSAT", NULL },
  { 89, "3", NULL },
};

const TOperator operators_514[1] = { // TLS
  { 2, "TLS-TT", NULL },
};

const TOperator operators_515[5] = { // PHL
  { 1, "Islacom", NULL },
  { 2, "GLOBE", NULL },
  { 3, "SMART Gold", NULL },
  { 5, "SUN", NULL },
  { 18, "CURE", NULL },
};

const TOperator operators_520[6] = { // THA
  { 1, "AIS GSM", NULL },
  { 10, "TH ORANGE", NULL },
  { 15, "TH ACT 1900", NULL },
  { 18, "DTAC", NULL },
  { 23, "GSM 1800", NULL },
  { 99, "TRUE", NULL },
};

const TOperator operators_525[6] = { // SGP
  { 1, "SingTel", NULL },
  { 2, "SingTel-G18", NULL },
  { 3, "SGP-M1-3GSM", NULL },
  { 4, "SGP-M1-3GSM", NULL },
  { 5, "STARHUB", NULL },
  { 7, "CallZone", NULL },
};

const TOperator operators_528[2] = { // BRU
  { 2, "BRU-bmobile", NULL },
  { 11, "DSTCom", NULL },
};

const TOperator operators_530[4] = { // NZL
  { 1, "vodafone NZ", NULL },
  { 4, "Next G NZ", NULL },
  { 5, "Telecom NZ", NULL },
  { 24, "2degrees", NULL },
};

const TOperator operators_537[2] = { // PNG
  { 1, "PNGBMobile", NULL },
  { 30, "Digicel PNG", NULL },
};

const TOperator operators_539[2] = { // TON
  { 1, "U-CALL", NULL },
  { 88, "Digicel", NULL },
};

const TOperator operators_540[1] = { // SLB
  { 1, "SI BREEZE", NULL },
};

const TOperator operators_541[2] = { // VUT
  { 1, "VUT SMILE", NULL },
  { 5, "DIGICEL", NULL },
};

const TOperator operators_542[1] = { // FJI
  { 1, "FJ VODAFONE", NULL },
};

const TOperator operators_544[1] = { // AS
  { 11, "Blue Sky", NULL },
};

const TOperator operators_545[1] = { // KIR
  { 9, "KL-Frigate", NULL },
};

const TOperator operators_546[1] = { // NCL
  { 1, "MOBILIS", NULL },
};

const TOperator operators_547[1] = { // FRA
  { 20, "VINI", NULL },
};

const TOperator operators_548[1] = { // COK
  { 1, "CK KOKANET", NULL },
};

const TOperator operators_549[1] = { // WSM
  { 27, "Samoatel GO", NULL },
};

const TOperator operators_550[1] = { // FSM
  { 1, "FSM Telecom", NULL },
};

const TOperator operators_552[1] = { // PLW
  { 80, "PLWPMC", NULL },
};

const TOperator operators_602[3] = { // EGY
  { 1, "MobiNiL", NULL },
  { 2, "vodafone EG", NULL },
  { 3, "etisalat", NULL },
};

const TOperator operators_603[3] = { // DZA
  { 1, "ALG Mobilis", NULL },
  { 2, "Djezzy", NULL },
  { 3, "DZA NEDJMA", NULL },
};

const TOperator operators_604[2] = { // MOR
  { 0, "MEDITEL", NULL },
  { 1, "IAM", NULL },
};

const TOperator operators_605[3] = { // TUN
  { 1, "Orange", NULL },
  { 2, "TUNTEL", NULL },
  { 3, "TUNISIANA", NULL },
};

const TOperator operators_606[2] = { // LBY
  { 0, "Libyana", NULL },
  { 1, "Al Madar", NULL },
};

const TOperator operators_607[4] = { // GMB
  { 1, "GAMCEL", NULL },
  { 2, "AFRICELL", NULL },
  { 3, "GM COMIUM", NULL },
  { 4, "QCell", NULL },
};

const TOperator operators_608[2] = { // SEN
  { 1, "ALIZE", NULL },
  { 2, "SENTEL", NULL },
};

const TOperator operators_609[1] = { // MRT
  { 1, "MR MATTEL", NULL },
};

const TOperator operators_610[2] = { // MLI
  { 1, "MALITEL ML", NULL },
  { 2, "ORANGE ML", NULL },
};

const TOperator operators_611[4] = { // GIN
  { 1, "Orange GN", NULL },
  { 2, "LAGUI", NULL },
  { 4, "GNAreeba", NULL },
  { 5, "GINCL", NULL },
};

const TOperator operators_612[5] = { // CIV
  { 1, "CI CORA", NULL },
  { 2, "MOOV-CI", NULL },
  { 3, "Orange CI", NULL },
  { 4, "KoZ", NULL },
  { 5, "MTN CI", NULL },
};

const TOperator operators_613[1] = { // BFA
  { 2, "BF Celtel", NULL },
};

const TOperator operators_614[4] = { // NER
  { 1, "SAHELCOM", NULL },
  { 2, "CELTEL", NULL },
  { 3, "NE TELECEL", NULL },
  { 4, "Orange NE", NULL },
};

const TOperator operators_615[2] = { // TGO
  { 1, "TOGO CELL", NULL },
  { 3, "TELECEL-TOGO", NULL },
};

const TOperator operators_616[4] = { // BEN
  { 2, "TLCL-BEN", NULL },
  { 3, "MTN BENIN", NULL },
  { 4, "BBCOM", NULL },
  { 5, "GloBenin", NULL },
};

const TOperator operators_617[2] = { // MRU
  { 1, "CELLPLUS-MRU", NULL },
  { 10, "EMTEL", NULL },
};

const TOperator operators_618[4] = { // LBR
  { 1, "LoneStar", NULL },
  { 2, "LIBERCELL", NULL },
  { 3, "Celcom GSM", NULL },
  { 7, "Celcom GSM", NULL },
};

const TOperator operators_619[3] = { // SLE
  { 1, "CELTEL SL", NULL },
  { 2, "MILLICOM SL", NULL },
  { 7, "GreenN SL", NULL },
};

const TOperator operators_620[4] = { // GHA
  { 1, "GH MTN", NULL },
  { 2, "GH ONEtouch", NULL },
  { 3, "tiGO", NULL },
  { 6, "GH Zain", NULL },
};

const TOperator operators_621[5] = { // NGA
  { 20, "Zain NG", NULL },
  { 30, "MTN - NG", NULL },
  { 40, "NG Mtel", NULL },
  { 50, "Gio NG", NULL },
  { 60, "EMTS NGA", NULL },
};

const TOperator operators_622[2] = { // TCD
  { 1, "CELTEL TCD", NULL },
  { 2, "TD LIBERTIS", NULL },
};

const TOperator operators_623[2] = { // CAF
  { 2, "Telecel", NULL },
  { 4, "NationLink", NULL },
};

const TOperator operators_624[2] = { // CMR
  { 1, "MTN CAM", NULL },
  { 2, "Orange CAM", NULL },
};

const TOperator operators_625[2] = { // CPV
  { 1, "CPV MOVEL", NULL },
  { 2, "CPV T+", NULL },
};

const TOperator operators_626[1] = { // STP
  { 1, "STP CSTmovel", NULL },
};

const TOperator operators_627[2] = { // GNQ
  { 1, "GNQ01", NULL },
  { 3, "HiTs-GQ", NULL },
};

const TOperator operators_628[3] = { // GAB
  { 1, "LIBERTIS", NULL },
  { 2, "GAB TELECEL", NULL },
  { 3, "Zain GA", NULL },
};

const TOperator operators_629[3] = { // COG
  { 1, "CELTEL RC", NULL },
  { 7, "WARID RC", NULL },
  { 10, "COG MTN", NULL },
};

const TOperator operators_630[6] = { // COD
  { 1, "VODACOM CD", NULL },
  { 2, "CELTEL DRC", NULL },
  { 4, "CELLCO GSM", NULL },
  { 5, "SCELL CD", NULL },
  { 86, "CCT", NULL },
  { 89, "CD OASIS", NULL },
};

const TOperator operators_631[1] = { // AGO
  { 2, "UNITEL", NULL },
};

const TOperator operators_632[3] = { // GNB
  { 2, "MTN", NULL },
  { 3, "Orange BS", NULL },
  { 7, "GTM", NULL },
};

const TOperator operators_633[3] = { // SEZ
  { 1, "C&W SEY", NULL },
  { 2, "SC SmartCom", NULL },
  { 10, "AIRTEL", NULL },
};

const TOperator operators_634[3] = { // SDN
  { 1, "MobiTel", NULL },
  { 2, "MTN", NULL },
  { 5, "Vivacell", NULL },
};

const TOperator operators_635[3] = { // RWA
  { 10, "R-CELL", NULL },
  { 12, "RWTEL", NULL },
  { 13, "TIGO", NULL },
};

const TOperator operators_636[1] = { // ETH
  { 1, "ETH-MTN", NULL },
};

const TOperator operators_637[6] = { // SOM
  { 1, "SO Telesom", NULL },
  { 4, "SOMAFONE", NULL },
  { 30, "Som Golis", NULL },
  { 40, "SO/MONTYSOM", NULL },
  { 71, "SOMTEL", NULL },
  { 82, "Telsom", NULL },
};

const TOperator operators_638[1] = { // DJI
  { 1, "DJ EVATIS", NULL },
};

const TOperator operators_639[3] = { // KEN
  { 2, "Safaricom", NULL },
  { 3, "CELTEL", NULL },
  { 7, "GSM Telkom", NULL },
};

const TOperator operators_640[6] = { // TZA
  { 1, "TRITEL", NULL },
  { 2, "TIGO - TZ", NULL },
  { 3, "ZANTEL", NULL },
  { 4, "VodaCom", NULL },
  { 5, "celtel", NULL },
  { 9, "Hits TZ", NULL },
};

const TOperator operators_641[5] = { // UGA
  { 1, "CELTEL", NULL },
  { 10, "MTN-UGANDA", NULL },
  { 11, "UTL", NULL },
  { 14, "OUL", NULL },
  { 22, "WaridTel", NULL },
};

const TOperator operators_642[5] = { // BDI
  { 1, "BDI ECONET", NULL },
  { 2, "TEMPO-AF", NULL },
  { 3, "ONATEL BDI", NULL },
  { 7, "SMART", NULL },
  { 82, "TELECEL-BDI", NULL },
};

const TOperator operators_643[2] = { // MOZ
  { 1, "mCel", NULL },
  { 4, "VodaCom-MZ", NULL },
};

const TOperator operators_645[2] = { // ZMB
  { 1, "ZM CELTEL", NULL },
  { 2, "MTN ZM", NULL },
};

const TOperator operators_646[3] = { // MDG
  { 1, "ZAIN MG", NULL },
  { 2, "Orange MG", NULL },
  { 4, "TELMA", NULL },
};

const TOperator operators_647[3] = { // REU
  { 0, "Orange re", NULL },
  { 2, "F-OMT", NULL },
  { 10, "SFR REUNION", NULL },
};

const TOperator operators_648[3] = { // ZMB
  { 1, "ZW NET*ONE", NULL },
  { 3, "TELECEL", NULL },
  { 4, "ECONET", NULL },
};

const TOperator operators_649[2] = { // NAM
  { 1, "MTC NAMIBIA", NULL },
  { 3, "NAM Cell One", NULL },
};

const TOperator operators_650[2] = { // MWI
  { 1, "TNM", NULL },
  { 10, "CELTEL", NULL },
};

const TOperator operators_651[2] = { // LSO
  { 1, "Vodacom-LS", NULL },
  { 2, "EZI-CEL", NULL },
};

const TOperator operators_652[2] = { // BWA
  { 1, "MASCOM", NULL },
  { 2, "Orange", NULL },
};

const TOperator operators_653[1] = { // SWZ
  { 10, "Swazi-MTN", NULL },
};

const TOperator operators_654[1] = { // COM
  { 1, "HURI", NULL },
};

const TOperator operators_655[3] = { // ZAF
  { 1, "VodaCom", NULL },
  { 7, "Cell C", NULL },
  { 10, "MTN", NULL },
};

const TOperator operators_702[2] = { // BLZ
  { 67, "BTL", NULL },
  { 68, "INTELCO", NULL },
};

const TOperator operators_704[3] = { // GTM
  { 1, "Claro GTM", NULL },
  { 2, "Comcel GSM", NULL },
  { 3, "movistar", NULL },
};

const TOperator operators_706[5] = { // SLV
  { 1, "CLARO SLV", NULL },
  { 2, "Digicel", NULL },
  { 3, "TELEMOVIL", NULL },
  { 4, "movistar", NULL },
  { 10, "PERSONAL", NULL },
};

const TOperator operators_708[3] = { // HND
  { 1, "CLARO HND", NULL },
  { 2, "CELTELHND", NULL },
  { 30, "HT - 200", NULL },
};

const TOperator operators_710[4] = { // NIC
  { 21, "CLARO NIC", NULL },
  { 73, "CLARO NIC", NULL },
  { 300, "movistar", NULL },
  { 730, "SERCOM", NULL },
};

const TOperator operators_712[3] = { // CRI
  { 0, "I.C.E.", NULL },
  { 1, "I.C.E.", NULL },
  { 2, "I.C.E.", NULL },
};

const TOperator operators_714[3] = { // PAN
  { 1, "PANCW", NULL },
  { 3, "CLARO PA", NULL },
  { 20, "movistar", NULL },
};

const TOperator operators_716[3] = { // PER
  { 6, "MOVISTAR", NULL },
  { 10, "CLARO PER", NULL },
  { 17, "PERN3", NULL },
};

const TOperator operators_722[4] = { // ARG
  { 7, "movistar", NULL },
  { 34, "PERSONAL", NULL },
  { 35, "PORT-HABLE", NULL },
  { 310, "CLARO AR", NULL },
};

const TOperator operators_724[15] = { // BRA
  { 2, "TIM BRASIL", NULL },
  { 3, "TIM BRASIL", NULL },
  { 4, "TIM BRASIL", NULL },
  { 5, "Claro", NULL },
  { 6, "VIVO", NULL },
  { 10, "VIVO", NULL },
  { 11, "VIVO", NULL },
  { 15, "BRA SCTL", NULL },
  { 16, "BrTCel", NULL },
  { 23, "VIVO", NULL },
  { 24, "AMAZONIA", NULL },
  { 31, "Oi", NULL },
  { 32, "CTBC", NULL },
  { 33, "CTBC", NULL },
  { 34, "CTBC", NULL },
};

const TOperator operators_730[4] = { // CHL
  { 1, "ENTEL PCS", NULL },
  { 2, "movistar", NULL },
  { 3, "CLARO CHL", NULL },
  { 10, "ENTEL PCS", NULL },
};

const TOperator operators_732[4] = { // COL
  { 101, "COMCEL", NULL },
  { 103, "TIGO COL", NULL },
  { 111, "TIGO COL", NULL },
  { 123, "movistar", NULL },
};

const TOperator operators_734[5] = { // VEN
  { 1, "INFONET", NULL },
  { 2, "DIGITEL", NULL },
  { 3, "DIGITEL", NULL },
  { 4, "movistar", NULL },
  { 6, "VE MOVILNET", NULL },
};

const TOperator operators_736[3] = { // BOL
  { 1, "VIVA", NULL },
  { 2, "EMOVIL", NULL },
  { 3, "Telecel", NULL },
};

const TOperator operators_738[2] = { // GUY
  { 1, "DIGICEL", NULL },
  { 2, "GUY CLNK PLS", NULL },
};

const TOperator operators_740[2] = { // ECU
  { 0, "movistar", NULL },
  { 1, "PORTA GSM", NULL },
};

const TOperator operators_744[3] = { // PRY
  { 1, "VOX", NULL },
  { 2, "CLARO PY", NULL },
  { 4, "Telecel GSM", NULL },
};

const TOperator operators_746[4] = { // SUR
  { 1, "ICMS", NULL },
  { 2, "TeleG", NULL },
  { 3, "DIGICEL", NULL },
  { 4, "UNIQA", NULL },
};

const TOperator operators_748[2] = { // URY
  { 7, "MOVISTAR", NULL },
  { 10, "CLARO UY", NULL },
};

const TOperator operators_750[1] = { // FLK
  { 1, "C&W FLK", NULL },
};

const TOperator operators_795[2] = { // TKM
  { 1, "MTS TM", NULL },
  { 2, "TM CELL", NULL },
};

const TOperator operators_901[8] = { // NOR
  { 5, "Thuraya", NULL },
  { 6, "Thuraya", NULL },
  { 12, "MCP", NULL },
  { 14, "AeroMobile", NULL },
  { 15, "OnAir", NULL },
  { 17, "Navitas", NULL },
  { 18, "WMS", NULL },
  { 21, "Seanet", NULL },
};


// Country data
const TCountry countrylist[222] = {
  { 1, "001", 1, operators_1 },
  { 2, "002", 1, operators_2 },
  { 202, "GRC", 4, operators_202 },
  { 204, "NLD", 5, operators_204 },
  { 206, "BEL", 3, operators_206 },
  { 208, "FRA", 6, operators_208 },
  { 212, "MCO", 1, operators_212 },
  { 213, "AND", 1, operators_213 },
  { 214, "ESP", 5, operators_214 },
  { 216, "HU", 3, operators_216 },
  { 218, "BIH", 3, operators_218 },
  { 219, "HRV", 3, operators_219 },
  { 220, "SCG", 5, operators_220 },
  { 222, "ITA", 5, operators_222 },
  { 226, "ROU", 4, operators_226 },
  { 228, "CHE", 5, operators_228 },
  { 230, "CZE", 3, operators_230 },
  { 231, "SVK", 3, operators_231 },
  { 232, "AUT", 6, operators_232 },
  { 234, "GBR", 14, operators_234 },
  { 238, "DNK", 6, operators_238 },
  { 240, "SWE", 8, operators_240 },
  { 242, "NOR", 4, operators_242 },
  { 244, "FIN", 7, operators_244 },
  { 246, "LTU", 3, operators_246 },
  { 247, "LVA", 3, operators_247 },
  { 248, "EST", 3, operators_248 },
  { 250, "RUS", 24, operators_250 },
  { 255, "UKR", 5, operators_255 },
  { 257, "BLR", 4, operators_257 },
  { 259, "MDA", 3, operators_259 },
  { 260, "POL", 4, operators_260 },
  { 262, "DEU", 7, operators_262 },
  { 266, "GIB", 2, operators_266 },
  { 268, "PRT", 3, operators_268 },
  { 270, "LUX", 3, operators_270 },
  { 272, "IRL", 4, operators_272 },
  { 274, "ISL", 6, operators_274 },
  { 276, "ALB", 4, operators_276 },
  { 278, "MLT", 3, operators_278 },
  { 280, "CYP", 2, operators_280 },
  { 282, "GEO", 4, operators_282 },
  { 283, "ARM", 3, operators_283 },
  { 284, "BGR", 3, operators_284 },
  { 286, "TUR", 4, operators_286 },
  { 288, "FRO", 2, operators_288 },
  { 290, "GRL", 1, operators_290 },
  { 292, "RSM", 1, operators_292 },
  { 293, "SVN", 4, operators_293 },
  { 294, "MKD", 3, operators_294 },
  { 295, "LIE", 4, operators_295 },
  { 302, "CAN", 9, operators_302 },
  { 308, "SPM", 2, operators_308 },
  { 310, "USA", 79, operators_310 },
  { 311, "USA", 25, operators_311 },
  { 312, "USA", 0, NULL },
  { 313, "USA", 0, NULL },
  { 314, "USA", 0, NULL },
  { 315, "USA", 0, NULL },
  { 316, "USA", 0, NULL },
  { 330, "PRI", 1, operators_330 },
  { 332, "USA", 1, operators_332 },
  { 334, "MEX", 2, operators_334 },
  { 338, "JAM", 4, operators_338 },
  { 340, "FRA", 5, operators_340 },
  { 342, "BRB", 4, operators_342 },
  { 344, "ATG", 3, operators_344 },
  { 346, "CYM", 1, operators_346 },
  { 348, "VGB", 2, operators_348 },
  { 350, "BDA", 4, operators_350 },
  { 352, "GRD", 4, operators_352 },
  { 354, "MS", 1, operators_354 },
  { 356, "KNA", 1, operators_356 },
  { 358, "SLU", 3, operators_358 },
  { 360, "VCT", 3, operators_360 },
  { 362, "ANT", 5, operators_362 },
  { 363, "ABW", 2, operators_363 },
  { 364, "BHS", 1, operators_364 },
  { 365, "AIA", 1, operators_365 },
  { 366, "DMA", 2, operators_366 },
  { 368, "CUB", 1, operators_368 },
  { 370, "DOM", 2, operators_370 },
  { 372, "HTI", 1, operators_372 },
  { 374, "TTO", 1, operators_374 },
  { 376, "TCA", 2, operators_376 },
  { 400, "AZE", 3, operators_400 },
  { 401, "KAZ", 3, operators_401 },
  { 402, "BTN", 2, operators_402 },
  { 404, "IND", 91, operators_404 },
  { 405, "IND", 147, operators_405 },
  { 410, "PAK", 5, operators_410 },
  { 412, "AFG", 4, operators_412 },
  { 413, "SRI", 6, operators_413 },
  { 414, "MMR", 1, operators_414 },
  { 415, "LBN", 3, operators_415 },
  { 416, "JOR", 3, operators_416 },
  { 417, "SYR", 4, operators_417 },
  { 418, "IRQ", 5, operators_418 },
  { 419, "KWT", 3, operators_419 },
  { 420, "KSA", 3, operators_420 },
  { 421, "YEM", 3, operators_421 },
  { 422, "OMN", 2, operators_422 },
  { 424, "UAE", 3, operators_424 },
  { 425, "ISR", 5, operators_425 },
  { 426, "BHR", 3, operators_426 },
  { 427, "QAT", 2, operators_427 },
  { 428, "MNG", 2, operators_428 },
  { 429, "NPL", 1, operators_429 },
  { 432, "IRN", 5, operators_432 },
  { 434, "UZB", 6, operators_434 },
  { 436, "TJK", 7, operators_436 },
  { 437, "KGZ", 3, operators_437 },
  { 438, "TKM", 1, operators_438 },
  { 440, "JPN", 3, operators_440 },
  { 450, "KOR", 3, operators_450 },
  { 452, "VMN", 4, operators_452 },
  { 454, "HKG", 13, operators_454 },
  { 455, "MAC", 5, operators_455 },
  { 456, "KHM", 8, operators_456 },
  { 457, "LAO", 4, operators_457 },
  { 460, "CHN", 2, operators_460 },
  { 466, "TWN", 8, operators_466 },
  { 467, "PRK", 1, operators_467 },
  { 470, "BGD", 5, operators_470 },
  { 472, "MDV", 2, operators_472 },
  { 502, "MYS", 8, operators_502 },
  { 505, "AUS", 6, operators_505 },
  { 510, "IDN", 6, operators_510 },
  { 514, "TLS", 1, operators_514 },
  { 515, "PHL", 5, operators_515 },
  { 520, "THA", 6, operators_520 },
  { 525, "SGP", 6, operators_525 },
  { 528, "BRU", 2, operators_528 },
  { 530, "NZL", 4, operators_530 },
  { 537, "PNG", 2, operators_537 },
  { 539, "TON", 2, operators_539 },
  { 540, "SLB", 1, operators_540 },
  { 541, "VUT", 2, operators_541 },
  { 542, "FJI", 1, operators_542 },
  { 544, "AS", 1, operators_544 },
  { 545, "KIR", 1, operators_545 },
  { 546, "NCL", 1, operators_546 },
  { 547, "FRA", 1, operators_547 },
  { 548, "COK", 1, operators_548 },
  { 549, "WSM", 1, operators_549 },
  { 550, "FSM", 1, operators_550 },
  { 552, "PLW", 1, operators_552 },
  { 602, "EGY", 3, operators_602 },
  { 603, "DZA", 3, operators_603 },
  { 604, "MOR", 2, operators_604 },
  { 605, "TUN", 3, operators_605 },
  { 606, "LBY", 2, operators_606 },
  { 607, "GMB", 4, operators_607 },
  { 608, "SEN", 2, operators_608 },
  { 609, "MRT", 1, operators_609 },
  { 610, "MLI", 2, operators_610 },
  { 611, "GIN", 4, operators_611 },
  { 612, "CIV", 5, operators_612 },
  { 613, "BFA", 1, operators_613 },
  { 614, "NER", 4, operators_614 },
  { 615, "TGO", 2, operators_615 },
  { 616, "BEN", 4, operators_616 },
  { 617, "MRU", 2, operators_617 },
  { 618, "LBR", 4, operators_618 },
  { 619, "SLE", 3, operators_619 },
  { 620, "GHA", 4, operators_620 },
  { 621, "NGA", 5, operators_621 },
  { 622, "TCD", 2, operators_622 },
  { 623, "CAF", 2, operators_623 },
  { 624, "CMR", 2, operators_624 },
  { 625, "CPV", 2, operators_625 },
  { 626, "STP", 1, operators_626 },
  { 627, "GNQ", 2, operators_627 },
  { 628, "GAB", 3, operators_628 },
  { 629, "COG", 3, operators_629 },
  { 630, "COD", 6, operators_630 },
  { 631, "AGO", 1, operators_631 },
  { 632, "GNB", 3, operators_632 },
  { 633, "SEZ", 3, operators_633 },
  { 634, "SDN", 3, operators_634 },
  { 635, "RWA", 3, operators_635 },
  { 636, "ETH", 1, operators_636 },
  { 637, "SOM", 6, operators_637 },
  { 638, "DJI", 1, operators_638 },
  { 639, "KEN", 3, operators_639 },
  { 640, "TZA", 6, operators_640 },
  { 641, "UGA", 5, operators_641 },
  { 642, "BDI", 5, operators_642 },
  { 643, "MOZ", 2, operators_643 },
  { 645, "ZMB", 2, operators_645 },
  { 646, "MDG", 3, operators_646 },
  { 647, "REU", 3, operators_647 },
  { 648, "ZMB", 3, operators_648 },
  { 649, "NAM", 2, operators_649 },
  { 650, "MWI", 2, operators_650 },
  { 651, "LSO", 2, operators_651 },
  { 652, "BWA", 2, operators_652 },
  { 653, "SWZ", 1, operators_653 },
  { 654, "COM", 1, operators_654 },
  { 655, "ZAF", 3, operators_655 },
  { 702, "BLZ", 2, operators_702 },
  { 704, "GTM", 3, operators_704 },
  { 706, "SLV", 5, operators_706 },
  { 708, "HND", 3, operators_708 },
  { 710, "NIC", 4, operators_710 },
  { 712, "CRI", 3, operators_712 },
  { 714, "PAN", 3, operators_714 },
  { 716, "PER", 3, operators_716 },
  { 722, "ARG", 4, operators_722 },
  { 724, "BRA", 15, operators_724 },
  { 730, "CHL", 4, operators_730 },
  { 732, "COL", 4, operators_732 },
  { 734, "VEN", 5, operators_734 },
  { 736, "BOL", 3, operators_736 },
  { 738, "GUY", 2, operators_738 },
  { 740, "ECU", 2, operators_740 },
  { 744, "PRY", 3, operators_744 },
  { 746, "SUR", 4, operators_746 },
  { 748, "URY", 2, operators_748 },
  { 750, "FLK", 1, operators_750 },
  { 795, "TKM", 2, operators_795 },
  { 901, "NOR", 8, operators_901 },
};

